config/routes.rb
Rails.application.routes.draw do
  get 'goal/index'

  get 'mission/index'

  get 'site/index'

  resources :invoices
  resources :delivery_statuses
  resources :payment_types
  resources :products
  resources :categories
  resources :product_units

   root 'products#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/delivery_status.rb
class DeliveryStatus < ActiveRecord::Base
  has_many :invoices
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :payment_type
  belongs_to :delivery_status
  has_and_belongs_to_many :products
end

app/models/invoices_product.rb
class InvoicesProduct < ActiveRecord::Base
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
  has_many :invoices
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :product_unit
  belongs_to :category
  has_and_belongs_to_many :invoices

end

app/models/product_unit.rb
class ProductUnit < ActiveRecord::Base
  has_many :products
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/controllers/delivery_statuses_controller.rb
class DeliveryStatusesController < ApplicationController
  before_action :set_delivery_status, only: [:show, :edit, :update, :destroy]

  # GET /delivery_statuses
  # GET /delivery_statuses.json
  def index
    @delivery_statuses = DeliveryStatus.all
  end

  # GET /delivery_statuses/1
  # GET /delivery_statuses/1.json
  def show
  end

  # GET /delivery_statuses/new
  def new
    @delivery_status = DeliveryStatus.new
  end

  # GET /delivery_statuses/1/edit
  def edit
  end

  # POST /delivery_statuses
  # POST /delivery_statuses.json
  def create
    @delivery_status = DeliveryStatus.new(delivery_status_params)

    respond_to do |format|
      if @delivery_status.save
        format.html { redirect_to @delivery_status, notice: 'Delivery status was successfully created.' }
        format.json { render :show, status: :created, location: @delivery_status }
      else
        format.html { render :new }
        format.json { render json: @delivery_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /delivery_statuses/1
  # PATCH/PUT /delivery_statuses/1.json
  def update
    respond_to do |format|
      if @delivery_status.update(delivery_status_params)
        format.html { redirect_to @delivery_status, notice: 'Delivery status was successfully updated.' }
        format.json { render :show, status: :ok, location: @delivery_status }
      else
        format.html { render :edit }
        format.json { render json: @delivery_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /delivery_statuses/1
  # DELETE /delivery_statuses/1.json
  def destroy
    @delivery_status.destroy
    respond_to do |format|
      format.html { redirect_to delivery_statuses_url, notice: 'Delivery status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delivery_status
      @delivery_status = DeliveryStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def delivery_status_params
      params.require(:delivery_status).permit(:status_name)
    end
end

app/controllers/goal_controller.rb
class GoalController < ApplicationController
  def index
  end
end

app/controllers/mission_controller.rb
class MissionController < ApplicationController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/delivery_statuses_helper.rb
module DeliveryStatusesHelper
end

app/helpers/goal_helper.rb
module GoalHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/mission_helper.rb
module MissionHelper
end

app/helpers/payment_types_helper.rb
module PaymentTypesHelper
end

app/helpers/product_units_helper.rb
module ProductUnitsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/delivery_statuses/_form.html.erb
<%= form_for(@delivery_status) do |f| %>
  <% if @delivery_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@delivery_status.errors.count, "error") %> prohibited this delivery_status from being saved:</h2>

      <ul>
      <% @delivery_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status_name %><br>
    <%= f.text_field :status_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/delivery_statuses/edit.html.erb
<h1>Editing Delivery Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @delivery_status %> |
<%= link_to 'Back', delivery_statuses_path %>

app/views/delivery_statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Delivery Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Status name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @delivery_statuses.each do |delivery_status| %>
      <tr>
        <td><%= delivery_status.status_name %></td>
        <td><%= link_to 'Show', delivery_status %></td>
        <td><%= link_to 'Edit', edit_delivery_status_path(delivery_status) %></td>
        <td><%= link_to 'Destroy', delivery_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Delivery status', new_delivery_status_path %>

app/views/delivery_statuses/new.html.erb
<h1>New Delivery Status</h1>

<%= render 'form' %>

<%= link_to 'Back', delivery_statuses_path %>

app/views/delivery_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status name:</strong>
  <%= @delivery_status.status_name %>
</p>

<%= link_to 'Edit', edit_delivery_status_path(@delivery_status) %> |
<%= link_to 'Back', delivery_statuses_path %>