config/routes.rb
Rails.application.routes.draw do
  get 'goal/index'

  get 'mission/index'

  get 'site/index'

  resources :invoices
  resources :delivery_statuses
  resources :payment_types
  resources :products
  resources :categories
  resources :product_units

   root 'products#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/delivery_status.rb
class DeliveryStatus < ActiveRecord::Base
  has_many :invoices
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :payment_type
  belongs_to :delivery_status
  has_and_belongs_to_many :products
end

app/models/invoices_product.rb
class InvoicesProduct < ActiveRecord::Base
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
  has_many :invoices
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :product_unit
  belongs_to :category
  has_and_belongs_to_many :invoices

end

app/models/product_unit.rb
class ProductUnit < ActiveRecord::Base
  has_many :products
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/controllers/goal_controller.rb
class GoalController < ApplicationController
  def index
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:total_amount_purchased, :purchase_date, :payment_type_id, :delivery_address, :delivery_date, :recieve_date, :delivery_status_id, :customer_name, :customer_email, :customerphone)
    end
end

app/controllers/mission_controller.rb
class MissionController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:searchbox].nil?
      @products = Product.all
    else
      params[:searchbox].downcase!
      @products = Product.where("product_name LIKE ? OR description LIKE ?", "%#{params[:searchbox]}%" , "%#{params[:searchbox]}%")
    end

  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    params[:product][:product_name].downcase!
    params[:product][:description].downcase!
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update

    params[:product][:product_name].downcase!
    params[:product][:description].downcase!
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_name, :price, :amount_in_stock, :product_unit_id, :category_id,:package_size,:description,:searchbox)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/delivery_statuses_helper.rb
module DeliveryStatusesHelper
end

app/helpers/goal_helper.rb
module GoalHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/mission_helper.rb
module MissionHelper
end

app/helpers/payment_types_helper.rb
module PaymentTypesHelper
end

app/helpers/product_units_helper.rb
module ProductUnitsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :total_amount_purchased %><br>
    <%= f.text_field :total_amount_purchased %>
  </div>
  <div class="field">
    <%= f.label :purchase_date %><br>
    <%= f.datetime_select :purchase_date %>
  </div>
  <div class="field">
    <%= f.label :payment_type_id %><br>
    <%= f.text_field :payment_type_id %>
  </div>
  <div class="field">
    <%= f.label :delivery_address %><br>
    <%= f.text_area :delivery_address %>
  </div>
  <div class="field">
    <%= f.label :delivery_date %><br>
    <%= f.datetime_select :delivery_date %>
  </div>
  <div class="field">
    <%= f.label :recieve_date %><br>
    <%= f.datetime_select :recieve_date %>
  </div>
  <div class="field">
    <%= f.label :delivery_status_id %><br>
    <%= f.text_field :delivery_status_id %>
  </div>
  <div class="field">
    <%= f.label :customer_name %><br>
    <%= f.text_field :customer_name %>
  </div>
  <div class="field">
    <%= f.label :customer_email %><br>
    <%= f.text_field :customer_email %>
  </div>
  <div class="field">
    <%= f.label :customerphone %><br>
    <%= f.text_field :customerphone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Total amount purchased</th>
      <th>Purchase date</th>
      <th>Payment type</th>
      <th>Delivery address</th>
      <th>Delivery date</th>
      <th>Recieve date</th>
      <th>Delivery status</th>
      <th>Customer name</th>
      <th>Customer email</th>
      <th>Customerphone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.total_amount_purchased %></td>
        <td><%= invoice.purchase_date %></td>
        <td><%= invoice.payment_type %></td>
        <td><%= invoice.delivery_address %></td>
        <td><%= invoice.delivery_date %></td>
        <td><%= invoice.recieve_date %></td>
        <td><%= invoice.delivery_status %></td>
        <td><%= invoice.customer_name %></td>
        <td><%= invoice.customer_email %></td>
        <td><%= invoice.customerphone %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Total amount purchased:</strong>
  <%= @invoice.total_amount_purchased %>
</p>

<p>
  <strong>Purchase date:</strong>
  <%= @invoice.purchase_date %>
</p>

<p>
  <strong>Payment type:</strong>
  <%= @invoice.payment_type %>
</p>

<p>
  <strong>Delivery address:</strong>
  <%= @invoice.delivery_address %>
</p>

<p>
  <strong>Delivery date:</strong>
  <%= @invoice.delivery_date %>
</p>

<p>
  <strong>Recieve date:</strong>
  <%= @invoice.recieve_date %>
</p>

<p>
  <strong>Delivery status:</strong>
  <%= @invoice.delivery_status %>
</p>

<p>
  <strong>Customer name:</strong>
  <%= @invoice.customer_name %>
</p>

<p>
  <strong>Customer email:</strong>
  <%= @invoice.customer_email %>
</p>

<p>
  <strong>Customerphone:</strong>
  <%= @invoice.customerphone %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_name %><br>
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :amount_in_stock %><br>
    <%= f.text_field :amount_in_stock %>
  </div>
    <div class="field">
      <%= f.label :package_size %><br>
      <%= f.text_field :package_size %>
    </div>
    <div class="field">
      <%= f.label :product_unit_id %><br>
      <%= f.collection_select :product_unit_id,ProductUnit.all,:id,:product_unit_name, {:prompt => 'Please select unit of the product'} %>
    </div>
    <div class="field">
      <%= f.label :category_id %><br>
      <%= f.collection_select :category_id,Category.all,:id,:category_name, {:prompt => 'Please select category'} %>
    </div>

    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="span9">
  <div class="hero-unit">
    <h1 class="">Special Offer</h1>
    <p class="">here is the best offer of the month! Do not loose it!</p>
    <p><a href="#" class="btn btn-primary btn-large">Learn more »</a></p>
  </div>

  <ul class="thumbnails">

    <% @products.each do |product| %>

    <li class="span3">
      <div class="thumbnail">
        <img src="holder.js/300x200" alt="">
        <div class="caption">
          <h4><%= product.product_name.capitalize %></h4>
          <p><%= product.package_size %>&nbsp;<%= product.product_unit.product_unit_name %></p>
          <% if (product.amount_in_stock < 1)%>
              <p>
                Availability: <font color="red">Out of Stock</font>
              </p>
          <% elsif (product.amount_in_stock < 20) %>
              Availability: <font color="green"><%= product.amount_in_stock %> left in Stock</font>
          <% else %>
              Availability: <font color="green">In Stock</font>
          <%end%>
          <p><strike><%= product.price %> THB</strike>&nbsp;<%= product.price %> THB</p>
          <%= link_to 'View', product, class:"btn btn-primary" %>
          <a class="btn btn-success" href="#">Add to Cart</a>
        </div>
      </div>
    </li>
    <% end %>
    </ul>


  <br/>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="span9">
  <div class="row">
    <div class="span5">
      <div id="items-carousel" class="carousel slide mbottom0">
        <div class="carousel-inner">
          <div class="active item">
            <img class="media-object" src="holder.js/470x310" alt="" />
          </div>

          <div class="item">
            <img class="media-object" src="holder.js/470x310" alt="" />
          </div>

          <div class="item">
            <img class="media-object" src="holder.js/470x310" alt="" />
          </div>
        </div>
        <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
      </div>
    </div>

    <div class="span4">
      <h4><%= @product.product_name %></h4>
      <h5>Product id : <%= @product.id %></h5>
      <p> <strong>Product unit:</strong> <%= @product.package_size %> <%= @product.product_unit.product_unit_abbreviation %> per package </p>
      <p> <strong>Category:</strong> <%= @product.category.category_name %> </p>
      <p><%= @product.description.capitalize %>
      <h4><%= @product.price %> &nbsp;THB</h4>
      <% if (@product.amount_in_stock < 1)%>
      <p>
        Availability: <font color="red">Out of Stock</font>
      </p>
      <% elsif (@product.amount_in_stock < 20) %>
          Availability: <font color="green"><%= @product.amount_in_stock %> left in Stock</font>
          <% else %>
          Availability: <font color="green">In Stock</font>
      <%end%>
      <form>

        <label>
          <input type="text" id="quantity" name="quantity" value="1" class="span1" />&nbsp;Qty
        </label>
        <button class="btn btn-primary">Add to Chart</button>
      </form>
      <a href="#">+ Add to whishlist</a>

    </div>
  </div>

</div>
</div>
</div>

<hr />

<p>
  <strong>Product name:</strong>
  <%= @product.product_name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Amount in stock:</strong>
  <%= @product.amount_in_stock %>
</p>

<p>
  <strong>Product unit:</strong>
  <%= @product.product_unit.product_unit_name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category.category_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description.capitalize %>
</p>



<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/site/index.html.erb
<h1>Hello visitors,</h1>
<p>Find some extra things in this page</p>