config/routes.rb
Rails.application.routes.draw do
  get 'goal/index'

  get 'mission/index'

  get 'site/index'

  resources :invoices
  resources :delivery_statuses
  resources :payment_types
  resources :products
  resources :categories
  resources :product_units

   root 'products#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/delivery_status.rb
class DeliveryStatus < ActiveRecord::Base
  has_many :invoices
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :payment_type
  belongs_to :delivery_status
  has_and_belongs_to_many :products
end

app/models/invoices_product.rb
class InvoicesProduct < ActiveRecord::Base
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
  has_many :invoices
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :product_unit
  belongs_to :category
  has_and_belongs_to_many :invoices

end

app/models/product_unit.rb
class ProductUnit < ActiveRecord::Base
  has_many :products
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/controllers/goal_controller.rb
class GoalController < ApplicationController
  def index
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:total_amount_purchased, :purchase_date, :payment_type_id, :delivery_address, :delivery_date, :recieve_date, :delivery_status_id, :customer_name, :customer_email, :customerphone)
    end
end

app/controllers/mission_controller.rb
class MissionController < ApplicationController
  def index
  end
end

app/controllers/payment_types_controller.rb
class PaymentTypesController < ApplicationController
  before_action :set_payment_type, only: [:show, :edit, :update, :destroy]

  # GET /payment_types
  # GET /payment_types.json
  def index
    @payment_types = PaymentType.all
  end

  # GET /payment_types/1
  # GET /payment_types/1.json
  def show
  end

  # GET /payment_types/new
  def new
    @payment_type = PaymentType.new
  end

  # GET /payment_types/1/edit
  def edit
  end

  # POST /payment_types
  # POST /payment_types.json
  def create
    @payment_type = PaymentType.new(payment_type_params)

    respond_to do |format|
      if @payment_type.save
        format.html { redirect_to @payment_type, notice: 'Payment type was successfully created.' }
        format.json { render :show, status: :created, location: @payment_type }
      else
        format.html { render :new }
        format.json { render json: @payment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_types/1
  # PATCH/PUT /payment_types/1.json
  def update
    respond_to do |format|
      if @payment_type.update(payment_type_params)
        format.html { redirect_to @payment_type, notice: 'Payment type was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_type }
      else
        format.html { render :edit }
        format.json { render json: @payment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_types/1
  # DELETE /payment_types/1.json
  def destroy
    @payment_type.destroy
    respond_to do |format|
      format.html { redirect_to payment_types_url, notice: 'Payment type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_type
      @payment_type = PaymentType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_type_params
      params.require(:payment_type).permit(:name_of_payment_type)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/goal_helper.rb
module GoalHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/mission_helper.rb
module MissionHelper
end

app/helpers/payment_types_helper.rb
module PaymentTypesHelper
end

app/helpers/product_units_helper.rb
module ProductUnitsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/payment_types/_form.html.erb
<%= form_for(@payment_type) do |f| %>
  <% if @payment_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment_type.errors.count, "error") %> prohibited this payment_type from being saved:</h2>

      <ul>
      <% @payment_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_of_payment_type %><br>
    <%= f.text_field :name_of_payment_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payment_types/edit.html.erb
<h1>Editing Payment Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_type %> |
<%= link_to 'Back', payment_types_path %>

app/views/payment_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Payment Types</h1>

<table>
  <thead>
    <tr>
      <th>Name of payment type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_types.each do |payment_type| %>
      <tr>
        <td><%= payment_type.name_of_payment_type %></td>
        <td><%= link_to 'Show', payment_type %></td>
        <td><%= link_to 'Edit', edit_payment_type_path(payment_type) %></td>
        <td><%= link_to 'Destroy', payment_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment type', new_payment_type_path %>

app/views/payment_types/new.html.erb
<h1>New Payment Type</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_types_path %>

app/views/payment_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name of payment type:</strong>
  <%= @payment_type.name_of_payment_type %>
</p>

<%= link_to 'Edit', edit_payment_type_path(@payment_type) %> |
<%= link_to 'Back', payment_types_path %>