config/routes.rb
Rails.application.routes.draw do
  get 'goal/index'

  get 'mission/index'

  get 'site/index'

  resources :invoices
  resources :delivery_statuses
  resources :payment_types
  resources :products
  resources :categories
  resources :product_units

   root 'products#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/delivery_status.rb
class DeliveryStatus < ActiveRecord::Base
  has_many :invoices
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :payment_type
  belongs_to :delivery_status
  has_and_belongs_to_many :products
end

app/models/invoices_product.rb
class InvoicesProduct < ActiveRecord::Base
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
  has_many :invoices
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :product_unit
  belongs_to :category
  has_and_belongs_to_many :invoices

end

app/models/product_unit.rb
class ProductUnit < ActiveRecord::Base
  has_many :products
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/controllers/goal_controller.rb
class GoalController < ApplicationController
  def index
  end
end

app/controllers/mission_controller.rb
class MissionController < ApplicationController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/goal_helper.rb
module GoalHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/mission_helper.rb
module MissionHelper
end

app/helpers/payment_types_helper.rb
module PaymentTypesHelper
end

app/helpers/product_units_helper.rb
module ProductUnitsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gourmet Supermarket</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse" type="button">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="/">Gourmet Supermarket</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin Menu <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'New Product', new_product_path %></li>
              <li><%= link_to('product_categories', categories_path) %></li>
              <li><%= link_to('delivery_status', delivery_statuses_path) %></li>
              <li><%= link_to('invoices', invoices_path) %></li>
              <li><%= link_to('payment type', payment_types_path) %></li>
              <li><%= link_to('product units', product_units_path) %></li>
              <li><% link_to('mission', mission_index_path)%></li>
            </ul>
          </li>
        </ul>
        <%= form_tag products_path, class:"navbar-form form-search pull-right", :method => 'get' do %>
            <p>
              <%= text_field_tag :searchbox, params[:searchbox] %>
              <%= submit_tag "Search product", :searchbox => nil, class:"btn" %>
            </p>
        <% end %>

      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span3">
      <div class="well">

        <div class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="icon-shopping-cart"></i>
            3 item - $999.99
            <b class="caret"></b></a>
          </a>
          <div class="dropdown-menu well" role="menu" aria-labelledby="dLabel">
            <p>Item x 1 <span class="pull-right">$333.33</span></p>
            <p>Item x 1 <span class="pull-right">$333.33</span></p>
            <p>Item x 1 <span class="pull-right">$333.33</span></p>
            <%= link_to "Checkout", new_invoice_path, class:"btn btn-primary"%>
          </div>
        </div>

      </div>

      <div class="well">
        <form class="form login-form">
          <h2>Sign in</h2>
          <div>
            <label>Username</label>
            <input id="Username" name="Username" type="text" style="width:150px;"/>

            <label>Password</label>
            <input id="Password" name="Password" type="password" style="width:150px;" />

            <label class="checkbox inline">
              <input type="checkbox" id="RememberMe" value="option1"> Remember me
            </label>

            <br /><br />

            <button type="submit" class="btn btn-success">Login</button>
          </div>
          <br />
          <a href="#">register</a>&nbsp;&#124;&nbsp;<a href="#">forgot password?</a>
        </form>
      </div>


      <!-- <div class="well">
        <ul class="nav nav-list">
          <li class="nav-header">Sidebar</li>
          <li class="active">
            <a href="#">Link</a>
          </li>
          <li>
            <a href="#">Link</a>
          </li>
          <li>
            <a href="#">Link</a>
          </li>

          <li class="nav-header">Sidebar</li>
          <li>
            <a href="#">Link</a>
          </li>
          <li>
            <a href="#">Link</a>
          </li>
          <li>
            <a href="#">Link</a>
          </li>

          <li class="nav-header">Sidebar</li>
          <li>
            <a href="#">Link</a>
          </li>
          <li>
            <a href="#">Link</a>
          </li>
          <li>
            <a href="#">Link</a>
          </li>
        </ul>
      </div>
-->
      <div class="well">
        <h4>Filters</h4>
        <form>
          <label class="checkbox">
            <input type="checkbox" value="">
            Filter 1
          </label>

          <label class="checkbox">
            <input type="checkbox" value="">
            Filter 1
          </label>

          <label class="checkbox">
            <input type="checkbox" value="">
            Filter 1
          </label>

          <label class="checkbox">
            <input type="checkbox" value="">
            Filter 1
          </label>
          <button class="btn btn-primary pull-right" type="submit">Filter</button>
        </form>
      </div>


    </div>




<%= yield %>
    <hr />
   <!-- <footer id="footer" class="vspace20">
      <div class="container">
        <div class="row">
          <div class="span4">
            <h4>Info</h4>
            <ul class="nav nav-stacked">
              <li><a href="#">Sell Conditions</a>
              <li><a href="#">Shipping Costs</a>
              <li><a href="#">Shipping Conditions</a>
              <li><a href="#">Returns</a>
              <li><a href="#">About Us</a>
            </ul>
          </div>

          <div class="span4">
            <h4>Location and Contacts</h4>
            <p><i class="icon-map-marker"></i>&nbsp;I do not Know Avenue, A City</p>
            <p><i class="icon-phone"></i>&nbsp;Phone: 234 739.126.72</p>
            <p><i class="icon-print"></i>&nbsp;Fax: 213 123.12.090</p>
            <p><i class="icon-envelope"></i>&nbsp;Email: info@mydomain.com</p>
            <p><i class="icon-globe"></i>&nbsp;Web: http://www.mydomain.com</p>
          </div>

          <div class="span4">
            <h4>Newsletter</h4>
            <p>Write you email to subscribe to our Newsletter service. Thanks!</p>
            <form class="form-newsletter">
              <div class="input-append">
                <input type="email" class="span2" placeholder="your email">
                <button type="submit" class="btn">Subscribe</button>
              </div>
            </form>
          </div>
        </div>

        <div class="row">
          <div class="span6">
            <p>&copy; Copyright 2012.&nbsp;<a href="#">Privacy</a>&nbsp;&amp;&nbsp;<a href="#">Terms and Conditions</a></p>
          </div>
          <div class="span6">
            <a class="pull-right" href="http://www.responsivewebmobile.com" target="_blank">credits by Responsive Web Mobile</a>
          </div>
        </div>
      </div>
    </footer> -->
</body>
</html>